package org.exmple.newbedwarshelper.client.esp.block;

import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.level.block.Block;

import java.util.ArrayList;
import java.util.List;

public final class EspBlockGroups {
    public static final EspBlockGroup ORES = new EspBlockGroup("ores", "screen.newbedwarshelper.esp_whitelist.block.group.ores", OresTargets.create());
    public static final EspBlockGroup PLANTS_AND_CROPS = new EspBlockGroup("plants_and_crops", "screen.newbedwarshelper.esp_whitelist.block.group.plants_and_crops", PlantsAndCropsTargets.create());
    public static final EspBlockGroup REDSTONE_COMPONENTS = new EspBlockGroup("redstone_components", "screen.newbedwarshelper.esp_whitelist.block.group.redstone_components", RedstoneComponentsTargets.create());
    public static final EspBlockGroup BUILDING_BLOCKS = new EspBlockGroup("building_blocks", "screen.newbedwarshelper.esp_whitelist.block.group.building_blocks", BuildingBlocksTargets.create());
    public static final EspBlockGroup FUNCTIONAL_BLOCKS = new EspBlockGroup("functional_blocks", "screen.newbedwarshelper.esp_whitelist.block.group.functional_blocks", FunctionalBlocksTargets.create());
    public static final EspBlockGroup MISC = new EspBlockGroup("misc", "screen.newbedwarshelper.esp_whitelist.block.group.misc", MiscTargets.create());
    public static final List<EspBlockGroup> ALL = List.of(
            ORES,
            PLANTS_AND_CROPS,
            REDSTONE_COMPONENTS,
            BUILDING_BLOCKS,
            FUNCTIONAL_BLOCKS,
            MISC
    );

    private EspBlockGroups() {
    }

    private static EspBlockTarget target(String id, EspBlockTargetColorMode colorMode, String... blockIds) {
        List<Block> blocks = new ArrayList<>();
        for (String blockId : blockIds) {
            blocks.add(BuiltInRegistries.BLOCK.getValue(Identifier.fromNamespaceAndPath("minecraft", blockId)));
        }
        return new EspBlockTarget(id, "block_target.newbedwarshelper." + id, List.copyOf(blocks), colorMode);
    }

    private static final class OresTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("ancient_debris", EspBlockTargetColorMode.DEFAULT, "ancient_debris"));
            targets.add(target("budding_amethyst", EspBlockTargetColorMode.DEFAULT, "budding_amethyst"));
            targets.add(target("clay", EspBlockTargetColorMode.DEFAULT, "clay"));
            targets.add(target("coal_block", EspBlockTargetColorMode.DEFAULT, "coal_block"));
            targets.add(target("coal_ore", EspBlockTargetColorMode.DEFAULT, "coal_ore"));
            targets.add(target("copper_ore", EspBlockTargetColorMode.DEFAULT, "copper_ore"));
            targets.add(target("deepslate_coal_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_coal_ore"));
            targets.add(target("deepslate_copper_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_copper_ore"));
            targets.add(target("deepslate_diamond_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_diamond_ore"));
            targets.add(target("deepslate_emerald_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_emerald_ore"));
            targets.add(target("deepslate_gold_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_gold_ore"));
            targets.add(target("deepslate_iron_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_iron_ore"));
            targets.add(target("deepslate_lapis_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_lapis_ore"));
            targets.add(target("deepslate_redstone_ore", EspBlockTargetColorMode.DEFAULT, "deepslate_redstone_ore"));
            targets.add(target("diamond_block", EspBlockTargetColorMode.DEFAULT, "diamond_block"));
            targets.add(target("diamond_ore", EspBlockTargetColorMode.DEFAULT, "diamond_ore"));
            targets.add(target("emerald_block", EspBlockTargetColorMode.DEFAULT, "emerald_block"));
            targets.add(target("emerald_ore", EspBlockTargetColorMode.DEFAULT, "emerald_ore"));
            targets.add(target("gilded_blackstone", EspBlockTargetColorMode.DEFAULT, "gilded_blackstone"));
            targets.add(target("glowstone", EspBlockTargetColorMode.DEFAULT, "glowstone"));
            targets.add(target("gold_block", EspBlockTargetColorMode.DEFAULT, "gold_block"));
            targets.add(target("gold_ore", EspBlockTargetColorMode.DEFAULT, "gold_ore"));
            targets.add(target("iron_block", EspBlockTargetColorMode.DEFAULT, "iron_block"));
            targets.add(target("iron_ore", EspBlockTargetColorMode.DEFAULT, "iron_ore"));
            targets.add(target("lapis_block", EspBlockTargetColorMode.DEFAULT, "lapis_block"));
            targets.add(target("lapis_ore", EspBlockTargetColorMode.DEFAULT, "lapis_ore"));
            targets.add(target("nether_gold_ore", EspBlockTargetColorMode.DEFAULT, "nether_gold_ore"));
            targets.add(target("nether_quartz_ore", EspBlockTargetColorMode.DEFAULT, "nether_quartz_ore"));
            targets.add(target("netherite_block", EspBlockTargetColorMode.DEFAULT, "netherite_block"));
            targets.add(target("raw_copper_block", EspBlockTargetColorMode.DEFAULT, "raw_copper_block"));
            targets.add(target("raw_gold_block", EspBlockTargetColorMode.DEFAULT, "raw_gold_block"));
            targets.add(target("raw_iron_block", EspBlockTargetColorMode.DEFAULT, "raw_iron_block"));
            targets.add(target("redstone_block", EspBlockTargetColorMode.DEFAULT, "redstone_block"));
            targets.add(target("redstone_ore", EspBlockTargetColorMode.DEFAULT, "redstone_ore"));
            return List.copyOf(targets);
        }
    }

    private static final class PlantsAndCropsTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("acacia_sapling", EspBlockTargetColorMode.DEFAULT, "acacia_sapling"));
            targets.add(target("allium", EspBlockTargetColorMode.DEFAULT, "allium"));
            targets.add(target("azure_bluet", EspBlockTargetColorMode.DEFAULT, "azure_bluet"));
            targets.add(target("bamboo", EspBlockTargetColorMode.DEFAULT, "bamboo", "bamboo_sapling"));
            targets.add(target("beetroots", EspBlockTargetColorMode.DEFAULT, "beetroots"));
            targets.add(target("big_dripleaf", EspBlockTargetColorMode.DEFAULT, "big_dripleaf"));
            targets.add(target("big_dripleaf_stem", EspBlockTargetColorMode.DEFAULT, "big_dripleaf_stem"));
            targets.add(target("birch_sapling", EspBlockTargetColorMode.DEFAULT, "birch_sapling"));
            targets.add(target("blue_orchid", EspBlockTargetColorMode.DEFAULT, "blue_orchid"));
            targets.add(target("brain_coral", EspBlockTargetColorMode.DEFAULT, "brain_coral"));
            targets.add(target("brown_mushroom", EspBlockTargetColorMode.DEFAULT, "brown_mushroom"));
            targets.add(target("bubble_coral", EspBlockTargetColorMode.DEFAULT, "bubble_coral"));
            targets.add(target("bush", EspBlockTargetColorMode.DEFAULT, "bush"));
            targets.add(target("cactus", EspBlockTargetColorMode.DEFAULT, "cactus"));
            targets.add(target("cactus_flower", EspBlockTargetColorMode.DEFAULT, "cactus_flower"));
            targets.add(target("carrots", EspBlockTargetColorMode.DEFAULT, "carrots"));
            targets.add(target("cave_vines", EspBlockTargetColorMode.DEFAULT, "cave_vines", "cave_vines_plant"));
            targets.add(target("cherry_sapling", EspBlockTargetColorMode.DEFAULT, "cherry_sapling"));
            targets.add(target("chorus_flower", EspBlockTargetColorMode.DEFAULT, "chorus_flower"));
            targets.add(target("chorus_plant", EspBlockTargetColorMode.DEFAULT, "chorus_plant"));
            targets.add(target("closed_eyeblossom", EspBlockTargetColorMode.DEFAULT, "closed_eyeblossom"));
            targets.add(target("cocoa", EspBlockTargetColorMode.DEFAULT, "cocoa"));
            targets.add(target("coral_fans", EspBlockTargetColorMode.DEFAULT, "brain_coral_fan", "brain_coral_wall_fan", "bubble_coral_fan", "bubble_coral_wall_fan", "fire_coral_fan", "fire_coral_wall_fan", "horn_coral_fan", "horn_coral_wall_fan", "tube_coral_fan", "tube_coral_wall_fan"));
            targets.add(target("cornflower", EspBlockTargetColorMode.DEFAULT, "cornflower"));
            targets.add(target("crimson_fungus", EspBlockTargetColorMode.DEFAULT, "crimson_fungus"));
            targets.add(target("crimson_roots", EspBlockTargetColorMode.DEFAULT, "crimson_roots"));
            targets.add(target("dandelion", EspBlockTargetColorMode.DEFAULT, "dandelion"));
            targets.add(target("dark_oak_sapling", EspBlockTargetColorMode.DEFAULT, "dark_oak_sapling"));
            targets.add(target("dead_brain_coral", EspBlockTargetColorMode.DEFAULT, "dead_brain_coral"));
            targets.add(target("dead_bubble_coral", EspBlockTargetColorMode.DEFAULT, "dead_bubble_coral"));
            targets.add(target("dead_bush", EspBlockTargetColorMode.DEFAULT, "dead_bush"));
            targets.add(target("dead_coral_fans", EspBlockTargetColorMode.DEFAULT, "dead_brain_coral_fan", "dead_brain_coral_wall_fan", "dead_bubble_coral_fan", "dead_bubble_coral_wall_fan", "dead_fire_coral_fan", "dead_fire_coral_wall_fan", "dead_horn_coral_fan", "dead_horn_coral_wall_fan", "dead_tube_coral_fan", "dead_tube_coral_wall_fan"));
            targets.add(target("dead_fire_coral", EspBlockTargetColorMode.DEFAULT, "dead_fire_coral"));
            targets.add(target("dead_horn_coral", EspBlockTargetColorMode.DEFAULT, "dead_horn_coral"));
            targets.add(target("dead_tube_coral", EspBlockTargetColorMode.DEFAULT, "dead_tube_coral"));
            targets.add(target("fern", EspBlockTargetColorMode.DEFAULT, "fern"));
            targets.add(target("fire_coral", EspBlockTargetColorMode.DEFAULT, "fire_coral"));
            targets.add(target("firefly_bush", EspBlockTargetColorMode.DEFAULT, "firefly_bush"));
            targets.add(target("glow_lichen", EspBlockTargetColorMode.DEFAULT, "glow_lichen"));
            targets.add(target("golden_dandelion", EspBlockTargetColorMode.DEFAULT, "golden_dandelion"));
            targets.add(target("hanging_roots", EspBlockTargetColorMode.DEFAULT, "hanging_roots"));
            targets.add(target("horn_coral", EspBlockTargetColorMode.DEFAULT, "horn_coral"));
            targets.add(target("jungle_sapling", EspBlockTargetColorMode.DEFAULT, "jungle_sapling"));
            targets.add(target("kelp", EspBlockTargetColorMode.DEFAULT, "kelp", "kelp_plant"));
            targets.add(target("large_fern", EspBlockTargetColorMode.DEFAULT, "large_fern"));
            targets.add(target("leaf_litter", EspBlockTargetColorMode.DEFAULT, "leaf_litter"));
            targets.add(target("lilac", EspBlockTargetColorMode.DEFAULT, "lilac"));
            targets.add(target("lily_of_the_valley", EspBlockTargetColorMode.DEFAULT, "lily_of_the_valley"));
            targets.add(target("lily_pad", EspBlockTargetColorMode.DEFAULT, "lily_pad"));
            targets.add(target("mangrove_propagule", EspBlockTargetColorMode.DEFAULT, "mangrove_propagule"));
            targets.add(target("melon_stem", EspBlockTargetColorMode.DEFAULT, "melon_stem", "attached_melon_stem"));
            targets.add(target("moss_carpet", EspBlockTargetColorMode.DEFAULT, "moss_carpet"));
            targets.add(target("nether_sprouts", EspBlockTargetColorMode.DEFAULT, "nether_sprouts"));
            targets.add(target("nether_wart", EspBlockTargetColorMode.DEFAULT, "nether_wart"));
            targets.add(target("oak_sapling", EspBlockTargetColorMode.DEFAULT, "oak_sapling"));
            targets.add(target("open_eyeblossom", EspBlockTargetColorMode.DEFAULT, "open_eyeblossom"));
            targets.add(target("orange_tulip", EspBlockTargetColorMode.DEFAULT, "orange_tulip"));
            targets.add(target("oxeye_daisy", EspBlockTargetColorMode.DEFAULT, "oxeye_daisy"));
            targets.add(target("pale_hanging_moss", EspBlockTargetColorMode.DEFAULT, "pale_hanging_moss"));
            targets.add(target("pale_moss_carpet", EspBlockTargetColorMode.DEFAULT, "pale_moss_carpet"));
            targets.add(target("pale_oak_sapling", EspBlockTargetColorMode.DEFAULT, "pale_oak_sapling"));
            targets.add(target("peony", EspBlockTargetColorMode.DEFAULT, "peony"));
            targets.add(target("pink_petals", EspBlockTargetColorMode.DEFAULT, "pink_petals"));
            targets.add(target("pink_tulip", EspBlockTargetColorMode.DEFAULT, "pink_tulip"));
            targets.add(target("pitcher_crop", EspBlockTargetColorMode.DEFAULT, "pitcher_crop"));
            targets.add(target("pitcher_plant", EspBlockTargetColorMode.DEFAULT, "pitcher_plant"));
            targets.add(target("poppy", EspBlockTargetColorMode.DEFAULT, "poppy"));
            targets.add(target("potatoes", EspBlockTargetColorMode.DEFAULT, "potatoes"));
            targets.add(target("pumpkin_stem", EspBlockTargetColorMode.DEFAULT, "pumpkin_stem", "attached_pumpkin_stem"));
            targets.add(target("red_mushroom", EspBlockTargetColorMode.DEFAULT, "red_mushroom"));
            targets.add(target("red_tulip", EspBlockTargetColorMode.DEFAULT, "red_tulip"));
            targets.add(target("rose_bush", EspBlockTargetColorMode.DEFAULT, "rose_bush"));
            targets.add(target("sea_pickle", EspBlockTargetColorMode.DEFAULT, "sea_pickle"));
            targets.add(target("seagrass", EspBlockTargetColorMode.DEFAULT, "seagrass"));
            targets.add(target("short_dry_grass", EspBlockTargetColorMode.DEFAULT, "short_dry_grass"));
            targets.add(target("short_grass", EspBlockTargetColorMode.DEFAULT, "short_grass"));
            targets.add(target("small_dripleaf", EspBlockTargetColorMode.DEFAULT, "small_dripleaf"));
            targets.add(target("spore_blossom", EspBlockTargetColorMode.DEFAULT, "spore_blossom"));
            targets.add(target("spruce_sapling", EspBlockTargetColorMode.DEFAULT, "spruce_sapling"));
            targets.add(target("sugar_cane", EspBlockTargetColorMode.DEFAULT, "sugar_cane"));
            targets.add(target("sunflower", EspBlockTargetColorMode.DEFAULT, "sunflower"));
            targets.add(target("sweet_berry_bush", EspBlockTargetColorMode.DEFAULT, "sweet_berry_bush"));
            targets.add(target("tall_dry_grass", EspBlockTargetColorMode.DEFAULT, "tall_dry_grass"));
            targets.add(target("tall_grass", EspBlockTargetColorMode.DEFAULT, "tall_grass"));
            targets.add(target("tall_seagrass", EspBlockTargetColorMode.DEFAULT, "tall_seagrass"));
            targets.add(target("torchflower", EspBlockTargetColorMode.DEFAULT, "torchflower"));
            targets.add(target("torchflower_crop", EspBlockTargetColorMode.DEFAULT, "torchflower_crop"));
            targets.add(target("tube_coral", EspBlockTargetColorMode.DEFAULT, "tube_coral"));
            targets.add(target("twisting_vines", EspBlockTargetColorMode.DEFAULT, "twisting_vines", "twisting_vines_plant"));
            targets.add(target("vine", EspBlockTargetColorMode.DEFAULT, "vine"));
            targets.add(target("warped_fungus", EspBlockTargetColorMode.DEFAULT, "warped_fungus"));
            targets.add(target("warped_roots", EspBlockTargetColorMode.DEFAULT, "warped_roots"));
            targets.add(target("weeping_vines", EspBlockTargetColorMode.DEFAULT, "weeping_vines", "weeping_vines_plant"));
            targets.add(target("wheat", EspBlockTargetColorMode.DEFAULT, "wheat"));
            targets.add(target("white_tulip", EspBlockTargetColorMode.DEFAULT, "white_tulip"));
            targets.add(target("wildflowers", EspBlockTargetColorMode.DEFAULT, "wildflowers"));
            targets.add(target("wither_rose", EspBlockTargetColorMode.DEFAULT, "wither_rose"));
            return List.copyOf(targets);
        }
    }

    private static final class RedstoneComponentsTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("activator_rail", EspBlockTargetColorMode.DEFAULT, "activator_rail"));
            targets.add(target("buttons", EspBlockTargetColorMode.DEFAULT, "acacia_button", "bamboo_button", "birch_button", "cherry_button", "crimson_button", "dark_oak_button", "jungle_button", "mangrove_button", "oak_button", "pale_oak_button", "polished_blackstone_button", "spruce_button", "stone_button", "warped_button"));
            targets.add(target("copper_bulb", EspBlockTargetColorMode.DEFAULT, "copper_bulb", "exposed_copper_bulb", "weathered_copper_bulb", "oxidized_copper_bulb"));
            targets.add(target("detector_rail", EspBlockTargetColorMode.DEFAULT, "detector_rail"));
            targets.add(target("heavy_weighted_pressure_plate", EspBlockTargetColorMode.DEFAULT, "heavy_weighted_pressure_plate"));
            targets.add(target("lever", EspBlockTargetColorMode.DEFAULT, "lever"));
            targets.add(target("light_weighted_pressure_plate", EspBlockTargetColorMode.DEFAULT, "light_weighted_pressure_plate"));
            targets.add(target("mangrove_roots", EspBlockTargetColorMode.DEFAULT, "mangrove_roots"));
            targets.add(target("note_block", EspBlockTargetColorMode.DEFAULT, "note_block"));
            targets.add(target("observer", EspBlockTargetColorMode.DEFAULT, "observer"));
            targets.add(target("piston", EspBlockTargetColorMode.DEFAULT, "piston"));
            targets.add(target("polished_blackstone_pressure_plate", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_pressure_plate"));
            targets.add(target("powered_rail", EspBlockTargetColorMode.DEFAULT, "powered_rail"));
            targets.add(target("rail", EspBlockTargetColorMode.DEFAULT, "rail"));
            targets.add(target("redstone_lamp", EspBlockTargetColorMode.DEFAULT, "redstone_lamp"));
            targets.add(target("redstone_wire", EspBlockTargetColorMode.DEFAULT, "redstone_wire"));
            targets.add(target("repeater", EspBlockTargetColorMode.DEFAULT, "repeater"));
            targets.add(target("sticky_piston", EspBlockTargetColorMode.DEFAULT, "sticky_piston"));
            targets.add(target("stone_pressure_plate", EspBlockTargetColorMode.DEFAULT, "stone_pressure_plate"));
            targets.add(target("target", EspBlockTargetColorMode.DEFAULT, "target"));
            targets.add(target("tnt", EspBlockTargetColorMode.DEFAULT, "tnt"));
            targets.add(target("tripwire", EspBlockTargetColorMode.DEFAULT, "tripwire"));
            targets.add(target("tripwire_hook", EspBlockTargetColorMode.DEFAULT, "tripwire_hook"));
            targets.add(target("waxed_copper_bulb", EspBlockTargetColorMode.DEFAULT, "waxed_copper_bulb", "waxed_exposed_copper_bulb", "waxed_weathered_copper_bulb", "waxed_oxidized_copper_bulb"));
            targets.add(target("wooden_pressure_plates", EspBlockTargetColorMode.DEFAULT, "oak_pressure_plate", "spruce_pressure_plate", "birch_pressure_plate", "jungle_pressure_plate", "acacia_pressure_plate", "dark_oak_pressure_plate", "mangrove_pressure_plate", "cherry_pressure_plate", "bamboo_pressure_plate", "crimson_pressure_plate", "warped_pressure_plate", "pale_oak_pressure_plate"));
            return List.copyOf(targets);
        }
    }

    private static final class BuildingBlocksTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("acacia_leaves", EspBlockTargetColorMode.DEFAULT, "acacia_leaves"));
            targets.add(target("acacia_log", EspBlockTargetColorMode.DEFAULT, "acacia_log"));
            targets.add(target("acacia_planks", EspBlockTargetColorMode.DEFAULT, "acacia_planks"));
            targets.add(target("acacia_slab", EspBlockTargetColorMode.DEFAULT, "acacia_slab"));
            targets.add(target("acacia_stairs", EspBlockTargetColorMode.DEFAULT, "acacia_stairs"));
            targets.add(target("acacia_wood", EspBlockTargetColorMode.DEFAULT, "acacia_wood"));
            targets.add(target("amethyst_block", EspBlockTargetColorMode.DEFAULT, "amethyst_block"));
            targets.add(target("amethyst_cluster", EspBlockTargetColorMode.DEFAULT, "amethyst_cluster"));
            targets.add(target("andesite", EspBlockTargetColorMode.DEFAULT, "andesite"));
            targets.add(target("andesite_slab", EspBlockTargetColorMode.DEFAULT, "andesite_slab"));
            targets.add(target("andesite_stairs", EspBlockTargetColorMode.DEFAULT, "andesite_stairs"));
            targets.add(target("andesite_wall", EspBlockTargetColorMode.DEFAULT, "andesite_wall"));
            targets.add(target("azalea", EspBlockTargetColorMode.DEFAULT, "azalea"));
            targets.add(target("azalea_leaves", EspBlockTargetColorMode.DEFAULT, "azalea_leaves"));
            targets.add(target("bamboo_block", EspBlockTargetColorMode.DEFAULT, "bamboo_block"));
            targets.add(target("bamboo_mosaic", EspBlockTargetColorMode.DEFAULT, "bamboo_mosaic"));
            targets.add(target("bamboo_mosaic_slab", EspBlockTargetColorMode.DEFAULT, "bamboo_mosaic_slab"));
            targets.add(target("bamboo_mosaic_stairs", EspBlockTargetColorMode.DEFAULT, "bamboo_mosaic_stairs"));
            targets.add(target("bamboo_planks", EspBlockTargetColorMode.DEFAULT, "bamboo_planks"));
            targets.add(target("bamboo_slab", EspBlockTargetColorMode.DEFAULT, "bamboo_slab"));
            targets.add(target("bamboo_stairs", EspBlockTargetColorMode.DEFAULT, "bamboo_stairs"));
            targets.add(target("basalt", EspBlockTargetColorMode.DEFAULT, "basalt"));
            targets.add(target("birch_leaves", EspBlockTargetColorMode.DEFAULT, "birch_leaves"));
            targets.add(target("birch_log", EspBlockTargetColorMode.DEFAULT, "birch_log"));
            targets.add(target("birch_planks", EspBlockTargetColorMode.DEFAULT, "birch_planks"));
            targets.add(target("birch_slab", EspBlockTargetColorMode.DEFAULT, "birch_slab"));
            targets.add(target("birch_stairs", EspBlockTargetColorMode.DEFAULT, "birch_stairs"));
            targets.add(target("birch_wood", EspBlockTargetColorMode.DEFAULT, "birch_wood"));
            targets.add(target("blackstone", EspBlockTargetColorMode.DEFAULT, "blackstone"));
            targets.add(target("blackstone_slab", EspBlockTargetColorMode.DEFAULT, "blackstone_slab"));
            targets.add(target("blackstone_stairs", EspBlockTargetColorMode.DEFAULT, "blackstone_stairs"));
            targets.add(target("blackstone_wall", EspBlockTargetColorMode.DEFAULT, "blackstone_wall"));
            targets.add(target("blue_ice", EspBlockTargetColorMode.DEFAULT, "blue_ice"));
            targets.add(target("bone_block", EspBlockTargetColorMode.DEFAULT, "bone_block"));
            targets.add(target("bookshelf", EspBlockTargetColorMode.DEFAULT, "bookshelf"));
            targets.add(target("brain_coral_block", EspBlockTargetColorMode.DEFAULT, "brain_coral_block"));
            targets.add(target("brick_slab", EspBlockTargetColorMode.DEFAULT, "brick_slab"));
            targets.add(target("brick_stairs", EspBlockTargetColorMode.DEFAULT, "brick_stairs"));
            targets.add(target("brick_wall", EspBlockTargetColorMode.DEFAULT, "brick_wall"));
            targets.add(target("bricks", EspBlockTargetColorMode.DEFAULT, "bricks"));
            targets.add(target("brown_mushroom_block", EspBlockTargetColorMode.DEFAULT, "brown_mushroom_block"));
            targets.add(target("bubble_coral_block", EspBlockTargetColorMode.DEFAULT, "bubble_coral_block"));
            targets.add(target("calcite", EspBlockTargetColorMode.DEFAULT, "calcite"));
            targets.add(target("candles", EspBlockTargetColorMode.DEFAULT, "candle", "white_candle", "orange_candle", "magenta_candle", "light_blue_candle", "yellow_candle", "lime_candle", "pink_candle", "gray_candle", "light_gray_candle", "cyan_candle", "purple_candle", "blue_candle", "brown_candle", "green_candle", "red_candle", "black_candle"));
            targets.add(target("carpets", EspBlockTargetColorMode.DEFAULT, "white_carpet", "orange_carpet", "magenta_carpet", "light_blue_carpet", "yellow_carpet", "lime_carpet", "pink_carpet", "gray_carpet", "light_gray_carpet", "cyan_carpet", "purple_carpet", "blue_carpet", "brown_carpet", "green_carpet", "red_carpet", "black_carpet"));
            targets.add(target("carved_pumpkin", EspBlockTargetColorMode.DEFAULT, "carved_pumpkin"));
            targets.add(target("cherry_leaves", EspBlockTargetColorMode.DEFAULT, "cherry_leaves"));
            targets.add(target("cherry_log", EspBlockTargetColorMode.DEFAULT, "cherry_log"));
            targets.add(target("cherry_planks", EspBlockTargetColorMode.DEFAULT, "cherry_planks"));
            targets.add(target("cherry_slab", EspBlockTargetColorMode.DEFAULT, "cherry_slab"));
            targets.add(target("cherry_stairs", EspBlockTargetColorMode.DEFAULT, "cherry_stairs"));
            targets.add(target("cherry_wood", EspBlockTargetColorMode.DEFAULT, "cherry_wood"));
            targets.add(target("chiseled_cinnabar", EspBlockTargetColorMode.DEFAULT, "chiseled_cinnabar"));
            targets.add(target("chiseled_copper", EspBlockTargetColorMode.DEFAULT, "chiseled_copper", "exposed_chiseled_copper", "weathered_chiseled_copper", "oxidized_chiseled_copper"));
            targets.add(target("chiseled_deepslate", EspBlockTargetColorMode.DEFAULT, "chiseled_deepslate"));
            targets.add(target("chiseled_nether_bricks", EspBlockTargetColorMode.DEFAULT, "chiseled_nether_bricks"));
            targets.add(target("chiseled_polished_blackstone", EspBlockTargetColorMode.DEFAULT, "chiseled_polished_blackstone"));
            targets.add(target("chiseled_quartz_block", EspBlockTargetColorMode.DEFAULT, "chiseled_quartz_block"));
            targets.add(target("chiseled_red_sandstone", EspBlockTargetColorMode.DEFAULT, "chiseled_red_sandstone"));
            targets.add(target("chiseled_resin_bricks", EspBlockTargetColorMode.DEFAULT, "chiseled_resin_bricks"));
            targets.add(target("chiseled_sandstone", EspBlockTargetColorMode.DEFAULT, "chiseled_sandstone"));
            targets.add(target("chiseled_stone_bricks", EspBlockTargetColorMode.DEFAULT, "chiseled_stone_bricks"));
            targets.add(target("chiseled_sulfur", EspBlockTargetColorMode.DEFAULT, "chiseled_sulfur"));
            targets.add(target("chiseled_tuff", EspBlockTargetColorMode.DEFAULT, "chiseled_tuff"));
            targets.add(target("chiseled_tuff_bricks", EspBlockTargetColorMode.DEFAULT, "chiseled_tuff_bricks"));
            targets.add(target("cinnabar", EspBlockTargetColorMode.DEFAULT, "cinnabar"));
            targets.add(target("cinnabar_brick_slab", EspBlockTargetColorMode.DEFAULT, "cinnabar_brick_slab"));
            targets.add(target("cinnabar_brick_stairs", EspBlockTargetColorMode.DEFAULT, "cinnabar_brick_stairs"));
            targets.add(target("cinnabar_brick_wall", EspBlockTargetColorMode.DEFAULT, "cinnabar_brick_wall"));
            targets.add(target("cinnabar_bricks", EspBlockTargetColorMode.DEFAULT, "cinnabar_bricks"));
            targets.add(target("cinnabar_slab", EspBlockTargetColorMode.DEFAULT, "cinnabar_slab"));
            targets.add(target("cinnabar_stairs", EspBlockTargetColorMode.DEFAULT, "cinnabar_stairs"));
            targets.add(target("cinnabar_wall", EspBlockTargetColorMode.DEFAULT, "cinnabar_wall"));
            targets.add(target("coarse_dirt", EspBlockTargetColorMode.DEFAULT, "coarse_dirt"));
            targets.add(target("cobbled_deepslate", EspBlockTargetColorMode.DEFAULT, "cobbled_deepslate"));
            targets.add(target("cobbled_deepslate_slab", EspBlockTargetColorMode.DEFAULT, "cobbled_deepslate_slab"));
            targets.add(target("cobbled_deepslate_stairs", EspBlockTargetColorMode.DEFAULT, "cobbled_deepslate_stairs"));
            targets.add(target("cobbled_deepslate_wall", EspBlockTargetColorMode.DEFAULT, "cobbled_deepslate_wall"));
            targets.add(target("cobblestone", EspBlockTargetColorMode.DEFAULT, "cobblestone"));
            targets.add(target("cobblestone_slab", EspBlockTargetColorMode.DEFAULT, "cobblestone_slab"));
            targets.add(target("cobblestone_stairs", EspBlockTargetColorMode.DEFAULT, "cobblestone_stairs"));
            targets.add(target("cobblestone_wall", EspBlockTargetColorMode.DEFAULT, "cobblestone_wall"));
            targets.add(target("cobweb", EspBlockTargetColorMode.DEFAULT, "cobweb"));
            targets.add(target("concrete", EspBlockTargetColorMode.DEFAULT, "white_concrete", "orange_concrete", "magenta_concrete", "light_blue_concrete", "yellow_concrete", "lime_concrete", "pink_concrete", "gray_concrete", "light_gray_concrete", "cyan_concrete", "purple_concrete", "blue_concrete", "brown_concrete", "green_concrete", "red_concrete", "black_concrete"));
            targets.add(target("concrete_powder", EspBlockTargetColorMode.DEFAULT, "white_concrete_powder", "orange_concrete_powder", "magenta_concrete_powder", "light_blue_concrete_powder", "yellow_concrete_powder", "lime_concrete_powder", "pink_concrete_powder", "gray_concrete_powder", "light_gray_concrete_powder", "cyan_concrete_powder", "purple_concrete_powder", "blue_concrete_powder", "brown_concrete_powder", "green_concrete_powder", "red_concrete_powder", "black_concrete_powder"));
            targets.add(target("copper_bars", EspBlockTargetColorMode.DEFAULT, "copper_bars", "exposed_copper_bars", "weathered_copper_bars", "oxidized_copper_bars"));
            targets.add(target("copper_block", EspBlockTargetColorMode.DEFAULT, "copper_block", "exposed_copper", "weathered_copper", "oxidized_copper"));
            targets.add(target("copper_chain", EspBlockTargetColorMode.DEFAULT, "copper_chain", "exposed_copper_chain", "weathered_copper_chain", "oxidized_copper_chain"));
            targets.add(target("copper_door", EspBlockTargetColorMode.DEFAULT, "copper_door", "exposed_copper_door", "weathered_copper_door", "oxidized_copper_door"));
            targets.add(target("copper_grate", EspBlockTargetColorMode.DEFAULT, "copper_grate", "exposed_copper_grate", "weathered_copper_grate", "oxidized_copper_grate"));
            targets.add(target("copper_lantern", EspBlockTargetColorMode.DEFAULT, "copper_lantern", "exposed_copper_lantern", "weathered_copper_lantern", "oxidized_copper_lantern"));
            targets.add(target("copper_torches", EspBlockTargetColorMode.DEFAULT, "copper_torch", "copper_wall_torch"));
            targets.add(target("copper_trapdoor", EspBlockTargetColorMode.DEFAULT, "copper_trapdoor", "exposed_copper_trapdoor", "weathered_copper_trapdoor", "oxidized_copper_trapdoor"));
            targets.add(target("cracked_deepslate_bricks", EspBlockTargetColorMode.DEFAULT, "cracked_deepslate_bricks"));
            targets.add(target("cracked_deepslate_tiles", EspBlockTargetColorMode.DEFAULT, "cracked_deepslate_tiles"));
            targets.add(target("cracked_nether_bricks", EspBlockTargetColorMode.DEFAULT, "cracked_nether_bricks"));
            targets.add(target("cracked_polished_blackstone_bricks", EspBlockTargetColorMode.DEFAULT, "cracked_polished_blackstone_bricks"));
            targets.add(target("cracked_stone_bricks", EspBlockTargetColorMode.DEFAULT, "cracked_stone_bricks"));
            targets.add(target("crimson_hyphae", EspBlockTargetColorMode.DEFAULT, "crimson_hyphae"));
            targets.add(target("crimson_nylium", EspBlockTargetColorMode.DEFAULT, "crimson_nylium"));
            targets.add(target("crimson_planks", EspBlockTargetColorMode.DEFAULT, "crimson_planks"));
            targets.add(target("crimson_slab", EspBlockTargetColorMode.DEFAULT, "crimson_slab"));
            targets.add(target("crimson_stairs", EspBlockTargetColorMode.DEFAULT, "crimson_stairs"));
            targets.add(target("crimson_stem", EspBlockTargetColorMode.DEFAULT, "crimson_stem"));
            targets.add(target("crying_obsidian", EspBlockTargetColorMode.DEFAULT, "crying_obsidian"));
            targets.add(target("cut_copper", EspBlockTargetColorMode.DEFAULT, "cut_copper", "exposed_cut_copper", "weathered_cut_copper", "oxidized_cut_copper"));
            targets.add(target("cut_copper_slab", EspBlockTargetColorMode.DEFAULT, "cut_copper_slab", "exposed_cut_copper_slab", "weathered_cut_copper_slab", "oxidized_cut_copper_slab"));
            targets.add(target("cut_copper_stairs", EspBlockTargetColorMode.DEFAULT, "cut_copper_stairs", "exposed_cut_copper_stairs", "weathered_cut_copper_stairs", "oxidized_cut_copper_stairs"));
            targets.add(target("cut_red_sandstone", EspBlockTargetColorMode.DEFAULT, "cut_red_sandstone"));
            targets.add(target("cut_red_sandstone_slab", EspBlockTargetColorMode.DEFAULT, "cut_red_sandstone_slab"));
            targets.add(target("cut_sandstone", EspBlockTargetColorMode.DEFAULT, "cut_sandstone"));
            targets.add(target("cut_sandstone_slab", EspBlockTargetColorMode.DEFAULT, "cut_sandstone_slab"));
            targets.add(target("dark_oak_leaves", EspBlockTargetColorMode.DEFAULT, "dark_oak_leaves"));
            targets.add(target("dark_oak_log", EspBlockTargetColorMode.DEFAULT, "dark_oak_log"));
            targets.add(target("dark_oak_planks", EspBlockTargetColorMode.DEFAULT, "dark_oak_planks"));
            targets.add(target("dark_oak_slab", EspBlockTargetColorMode.DEFAULT, "dark_oak_slab"));
            targets.add(target("dark_oak_stairs", EspBlockTargetColorMode.DEFAULT, "dark_oak_stairs"));
            targets.add(target("dark_oak_wood", EspBlockTargetColorMode.DEFAULT, "dark_oak_wood"));
            targets.add(target("dark_prismarine", EspBlockTargetColorMode.DEFAULT, "dark_prismarine"));
            targets.add(target("dark_prismarine_slab", EspBlockTargetColorMode.DEFAULT, "dark_prismarine_slab"));
            targets.add(target("dark_prismarine_stairs", EspBlockTargetColorMode.DEFAULT, "dark_prismarine_stairs"));
            targets.add(target("dead_brain_coral_block", EspBlockTargetColorMode.DEFAULT, "dead_brain_coral_block"));
            targets.add(target("dead_bubble_coral_block", EspBlockTargetColorMode.DEFAULT, "dead_bubble_coral_block"));
            targets.add(target("dead_fire_coral_block", EspBlockTargetColorMode.DEFAULT, "dead_fire_coral_block"));
            targets.add(target("dead_horn_coral_block", EspBlockTargetColorMode.DEFAULT, "dead_horn_coral_block"));
            targets.add(target("dead_tube_coral_block", EspBlockTargetColorMode.DEFAULT, "dead_tube_coral_block"));
            targets.add(target("deepslate", EspBlockTargetColorMode.DEFAULT, "deepslate"));
            targets.add(target("deepslate_brick_slab", EspBlockTargetColorMode.DEFAULT, "deepslate_brick_slab"));
            targets.add(target("deepslate_brick_stairs", EspBlockTargetColorMode.DEFAULT, "deepslate_brick_stairs"));
            targets.add(target("deepslate_brick_wall", EspBlockTargetColorMode.DEFAULT, "deepslate_brick_wall"));
            targets.add(target("deepslate_bricks", EspBlockTargetColorMode.DEFAULT, "deepslate_bricks"));
            targets.add(target("deepslate_tile_slab", EspBlockTargetColorMode.DEFAULT, "deepslate_tile_slab"));
            targets.add(target("deepslate_tile_stairs", EspBlockTargetColorMode.DEFAULT, "deepslate_tile_stairs"));
            targets.add(target("deepslate_tile_wall", EspBlockTargetColorMode.DEFAULT, "deepslate_tile_wall"));
            targets.add(target("deepslate_tiles", EspBlockTargetColorMode.DEFAULT, "deepslate_tiles"));
            targets.add(target("diorite", EspBlockTargetColorMode.DEFAULT, "diorite"));
            targets.add(target("diorite_slab", EspBlockTargetColorMode.DEFAULT, "diorite_slab"));
            targets.add(target("diorite_stairs", EspBlockTargetColorMode.DEFAULT, "diorite_stairs"));
            targets.add(target("diorite_wall", EspBlockTargetColorMode.DEFAULT, "diorite_wall"));
            targets.add(target("dirt", EspBlockTargetColorMode.DEFAULT, "dirt"));
            targets.add(target("dirt_path", EspBlockTargetColorMode.DEFAULT, "dirt_path"));
            targets.add(target("dried_kelp_block", EspBlockTargetColorMode.DEFAULT, "dried_kelp_block"));
            targets.add(target("dripstone_block", EspBlockTargetColorMode.DEFAULT, "dripstone_block"));
            targets.add(target("end_portal_frame", EspBlockTargetColorMode.DEFAULT, "end_portal_frame"));
            targets.add(target("end_rod", EspBlockTargetColorMode.DEFAULT, "end_rod"));
            targets.add(target("end_stone", EspBlockTargetColorMode.DEFAULT, "end_stone"));
            targets.add(target("end_stone_brick_slab", EspBlockTargetColorMode.DEFAULT, "end_stone_brick_slab"));
            targets.add(target("end_stone_brick_stairs", EspBlockTargetColorMode.DEFAULT, "end_stone_brick_stairs"));
            targets.add(target("end_stone_brick_wall", EspBlockTargetColorMode.DEFAULT, "end_stone_brick_wall"));
            targets.add(target("end_stone_bricks", EspBlockTargetColorMode.DEFAULT, "end_stone_bricks"));
            targets.add(target("farmland", EspBlockTargetColorMode.DEFAULT, "farmland"));
            targets.add(target("fence_gates", EspBlockTargetColorMode.DEFAULT, "oak_fence_gate", "spruce_fence_gate", "birch_fence_gate", "jungle_fence_gate", "acacia_fence_gate", "dark_oak_fence_gate", "mangrove_fence_gate", "cherry_fence_gate", "bamboo_fence_gate", "crimson_fence_gate", "warped_fence_gate", "pale_oak_fence_gate"));
            targets.add(target("fire_coral_block", EspBlockTargetColorMode.DEFAULT, "fire_coral_block"));
            targets.add(target("flower_pots", EspBlockTargetColorMode.DEFAULT, "flower_pot", "potted_acacia_sapling", "potted_allium", "potted_azalea_bush", "potted_azure_bluet", "potted_bamboo", "potted_birch_sapling", "potted_blue_orchid", "potted_brown_mushroom", "potted_cactus", "potted_cherry_sapling", "potted_closed_eyeblossom", "potted_cornflower", "potted_crimson_fungus", "potted_crimson_roots", "potted_dandelion", "potted_dark_oak_sapling", "potted_dead_bush", "potted_fern", "potted_flowering_azalea_bush", "potted_golden_dandelion", "potted_jungle_sapling", "potted_lily_of_the_valley", "potted_mangrove_propagule", "potted_oak_sapling", "potted_open_eyeblossom", "potted_orange_tulip", "potted_oxeye_daisy", "potted_pale_oak_sapling", "potted_pink_tulip", "potted_poppy", "potted_red_mushroom", "potted_red_tulip", "potted_spruce_sapling", "potted_torchflower", "potted_warped_fungus", "potted_warped_roots", "potted_white_tulip", "potted_wither_rose"));
            targets.add(target("flowering_azalea", EspBlockTargetColorMode.DEFAULT, "flowering_azalea"));
            targets.add(target("flowering_azalea_leaves", EspBlockTargetColorMode.DEFAULT, "flowering_azalea_leaves"));
            targets.add(target("glass", EspBlockTargetColorMode.DEFAULT, "glass"));
            targets.add(target("glass_pane", EspBlockTargetColorMode.DEFAULT, "glass_pane"));
            targets.add(target("glazed_terracotta", EspBlockTargetColorMode.DEFAULT, "white_glazed_terracotta", "orange_glazed_terracotta", "magenta_glazed_terracotta", "light_blue_glazed_terracotta", "yellow_glazed_terracotta", "lime_glazed_terracotta", "pink_glazed_terracotta", "gray_glazed_terracotta", "light_gray_glazed_terracotta", "cyan_glazed_terracotta", "purple_glazed_terracotta", "blue_glazed_terracotta", "brown_glazed_terracotta", "green_glazed_terracotta", "red_glazed_terracotta", "black_glazed_terracotta"));
            targets.add(target("granite", EspBlockTargetColorMode.DEFAULT, "granite"));
            targets.add(target("granite_slab", EspBlockTargetColorMode.DEFAULT, "granite_slab"));
            targets.add(target("granite_stairs", EspBlockTargetColorMode.DEFAULT, "granite_stairs"));
            targets.add(target("granite_wall", EspBlockTargetColorMode.DEFAULT, "granite_wall"));
            targets.add(target("grass_block", EspBlockTargetColorMode.DEFAULT, "grass_block"));
            targets.add(target("gravel", EspBlockTargetColorMode.DEFAULT, "gravel"));
            targets.add(target("hay_block", EspBlockTargetColorMode.DEFAULT, "hay_block"));
            targets.add(target("honey_block", EspBlockTargetColorMode.DEFAULT, "honey_block"));
            targets.add(target("honeycomb_block", EspBlockTargetColorMode.DEFAULT, "honeycomb_block"));
            targets.add(target("horn_coral_block", EspBlockTargetColorMode.DEFAULT, "horn_coral_block"));
            targets.add(target("ice", EspBlockTargetColorMode.DEFAULT, "ice"));
            targets.add(target("infested_chiseled_stone_bricks", EspBlockTargetColorMode.DEFAULT, "infested_chiseled_stone_bricks"));
            targets.add(target("infested_cobblestone", EspBlockTargetColorMode.DEFAULT, "infested_cobblestone"));
            targets.add(target("infested_cracked_stone_bricks", EspBlockTargetColorMode.DEFAULT, "infested_cracked_stone_bricks"));
            targets.add(target("infested_deepslate", EspBlockTargetColorMode.DEFAULT, "infested_deepslate"));
            targets.add(target("infested_mossy_stone_bricks", EspBlockTargetColorMode.DEFAULT, "infested_mossy_stone_bricks"));
            targets.add(target("infested_stone", EspBlockTargetColorMode.DEFAULT, "infested_stone"));
            targets.add(target("infested_stone_bricks", EspBlockTargetColorMode.DEFAULT, "infested_stone_bricks"));
            targets.add(target("iron_bars", EspBlockTargetColorMode.DEFAULT, "iron_bars"));
            targets.add(target("iron_chain", EspBlockTargetColorMode.DEFAULT, "iron_chain"));
            targets.add(target("iron_door", EspBlockTargetColorMode.DEFAULT, "iron_door"));
            targets.add(target("iron_trapdoor", EspBlockTargetColorMode.DEFAULT, "iron_trapdoor"));
            targets.add(target("jack_o_lantern", EspBlockTargetColorMode.DEFAULT, "jack_o_lantern"));
            targets.add(target("jungle_leaves", EspBlockTargetColorMode.DEFAULT, "jungle_leaves"));
            targets.add(target("jungle_log", EspBlockTargetColorMode.DEFAULT, "jungle_log"));
            targets.add(target("jungle_planks", EspBlockTargetColorMode.DEFAULT, "jungle_planks"));
            targets.add(target("jungle_slab", EspBlockTargetColorMode.DEFAULT, "jungle_slab"));
            targets.add(target("jungle_stairs", EspBlockTargetColorMode.DEFAULT, "jungle_stairs"));
            targets.add(target("jungle_wood", EspBlockTargetColorMode.DEFAULT, "jungle_wood"));
            targets.add(target("ladder", EspBlockTargetColorMode.DEFAULT, "ladder"));
            targets.add(target("lantern", EspBlockTargetColorMode.DEFAULT, "lantern"));
            targets.add(target("large_amethyst_bud", EspBlockTargetColorMode.DEFAULT, "large_amethyst_bud"));
            targets.add(target("magma_block", EspBlockTargetColorMode.DEFAULT, "magma_block"));
            targets.add(target("mangrove_leaves", EspBlockTargetColorMode.DEFAULT, "mangrove_leaves"));
            targets.add(target("mangrove_log", EspBlockTargetColorMode.DEFAULT, "mangrove_log"));
            targets.add(target("mangrove_planks", EspBlockTargetColorMode.DEFAULT, "mangrove_planks"));
            targets.add(target("mangrove_slab", EspBlockTargetColorMode.DEFAULT, "mangrove_slab"));
            targets.add(target("mangrove_stairs", EspBlockTargetColorMode.DEFAULT, "mangrove_stairs"));
            targets.add(target("mangrove_wood", EspBlockTargetColorMode.DEFAULT, "mangrove_wood"));
            targets.add(target("medium_amethyst_bud", EspBlockTargetColorMode.DEFAULT, "medium_amethyst_bud"));
            targets.add(target("melon", EspBlockTargetColorMode.DEFAULT, "melon"));
            targets.add(target("moss_block", EspBlockTargetColorMode.DEFAULT, "moss_block"));
            targets.add(target("mossy_cobblestone", EspBlockTargetColorMode.DEFAULT, "mossy_cobblestone"));
            targets.add(target("mossy_cobblestone_slab", EspBlockTargetColorMode.DEFAULT, "mossy_cobblestone_slab"));
            targets.add(target("mossy_cobblestone_stairs", EspBlockTargetColorMode.DEFAULT, "mossy_cobblestone_stairs"));
            targets.add(target("mossy_cobblestone_wall", EspBlockTargetColorMode.DEFAULT, "mossy_cobblestone_wall"));
            targets.add(target("mossy_stone_brick_slab", EspBlockTargetColorMode.DEFAULT, "mossy_stone_brick_slab"));
            targets.add(target("mossy_stone_brick_stairs", EspBlockTargetColorMode.DEFAULT, "mossy_stone_brick_stairs"));
            targets.add(target("mossy_stone_brick_wall", EspBlockTargetColorMode.DEFAULT, "mossy_stone_brick_wall"));
            targets.add(target("mossy_stone_bricks", EspBlockTargetColorMode.DEFAULT, "mossy_stone_bricks"));
            targets.add(target("mud", EspBlockTargetColorMode.DEFAULT, "mud"));
            targets.add(target("mud_brick_slab", EspBlockTargetColorMode.DEFAULT, "mud_brick_slab"));
            targets.add(target("mud_brick_stairs", EspBlockTargetColorMode.DEFAULT, "mud_brick_stairs"));
            targets.add(target("mud_brick_wall", EspBlockTargetColorMode.DEFAULT, "mud_brick_wall"));
            targets.add(target("mud_bricks", EspBlockTargetColorMode.DEFAULT, "mud_bricks"));
            targets.add(target("muddy_mangrove_roots", EspBlockTargetColorMode.DEFAULT, "muddy_mangrove_roots"));
            targets.add(target("mushroom_stem", EspBlockTargetColorMode.DEFAULT, "mushroom_stem"));
            targets.add(target("mycelium", EspBlockTargetColorMode.DEFAULT, "mycelium"));
            targets.add(target("nether_brick_fence", EspBlockTargetColorMode.DEFAULT, "nether_brick_fence"));
            targets.add(target("nether_brick_slab", EspBlockTargetColorMode.DEFAULT, "nether_brick_slab"));
            targets.add(target("nether_brick_stairs", EspBlockTargetColorMode.DEFAULT, "nether_brick_stairs"));
            targets.add(target("nether_brick_wall", EspBlockTargetColorMode.DEFAULT, "nether_brick_wall"));
            targets.add(target("nether_bricks", EspBlockTargetColorMode.DEFAULT, "nether_bricks"));
            targets.add(target("nether_wart_block", EspBlockTargetColorMode.DEFAULT, "nether_wart_block"));
            targets.add(target("netherrack", EspBlockTargetColorMode.DEFAULT, "netherrack"));
            targets.add(target("oak_leaves", EspBlockTargetColorMode.DEFAULT, "oak_leaves"));
            targets.add(target("oak_log", EspBlockTargetColorMode.DEFAULT, "oak_log"));
            targets.add(target("oak_planks", EspBlockTargetColorMode.DEFAULT, "oak_planks"));
            targets.add(target("oak_slab", EspBlockTargetColorMode.DEFAULT, "oak_slab"));
            targets.add(target("oak_stairs", EspBlockTargetColorMode.DEFAULT, "oak_stairs"));
            targets.add(target("oak_wood", EspBlockTargetColorMode.DEFAULT, "oak_wood"));
            targets.add(target("obsidian", EspBlockTargetColorMode.DEFAULT, "obsidian"));
            targets.add(target("ochre_froglight", EspBlockTargetColorMode.DEFAULT, "ochre_froglight"));
            targets.add(target("packed_ice", EspBlockTargetColorMode.DEFAULT, "packed_ice"));
            targets.add(target("packed_mud", EspBlockTargetColorMode.DEFAULT, "packed_mud"));
            targets.add(target("pale_moss_block", EspBlockTargetColorMode.DEFAULT, "pale_moss_block"));
            targets.add(target("pale_oak_leaves", EspBlockTargetColorMode.DEFAULT, "pale_oak_leaves"));
            targets.add(target("pale_oak_log", EspBlockTargetColorMode.DEFAULT, "pale_oak_log"));
            targets.add(target("pale_oak_planks", EspBlockTargetColorMode.DEFAULT, "pale_oak_planks"));
            targets.add(target("pale_oak_slab", EspBlockTargetColorMode.DEFAULT, "pale_oak_slab"));
            targets.add(target("pale_oak_stairs", EspBlockTargetColorMode.DEFAULT, "pale_oak_stairs"));
            targets.add(target("pale_oak_wood", EspBlockTargetColorMode.DEFAULT, "pale_oak_wood"));
            targets.add(target("pearlescent_froglight", EspBlockTargetColorMode.DEFAULT, "pearlescent_froglight"));
            targets.add(target("podzol", EspBlockTargetColorMode.DEFAULT, "podzol"));
            targets.add(target("pointed_dripstone", EspBlockTargetColorMode.DEFAULT, "pointed_dripstone"));
            targets.add(target("polished_andesite", EspBlockTargetColorMode.DEFAULT, "polished_andesite"));
            targets.add(target("polished_andesite_slab", EspBlockTargetColorMode.DEFAULT, "polished_andesite_slab"));
            targets.add(target("polished_andesite_stairs", EspBlockTargetColorMode.DEFAULT, "polished_andesite_stairs"));
            targets.add(target("polished_basalt", EspBlockTargetColorMode.DEFAULT, "polished_basalt"));
            targets.add(target("polished_blackstone", EspBlockTargetColorMode.DEFAULT, "polished_blackstone"));
            targets.add(target("polished_blackstone_brick_slab", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_brick_slab"));
            targets.add(target("polished_blackstone_brick_stairs", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_brick_stairs"));
            targets.add(target("polished_blackstone_brick_wall", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_brick_wall"));
            targets.add(target("polished_blackstone_bricks", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_bricks"));
            targets.add(target("polished_blackstone_slab", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_slab"));
            targets.add(target("polished_blackstone_stairs", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_stairs"));
            targets.add(target("polished_blackstone_wall", EspBlockTargetColorMode.DEFAULT, "polished_blackstone_wall"));
            targets.add(target("polished_cinnabar", EspBlockTargetColorMode.DEFAULT, "polished_cinnabar"));
            targets.add(target("polished_cinnabar_slab", EspBlockTargetColorMode.DEFAULT, "polished_cinnabar_slab"));
            targets.add(target("polished_cinnabar_stairs", EspBlockTargetColorMode.DEFAULT, "polished_cinnabar_stairs"));
            targets.add(target("polished_cinnabar_wall", EspBlockTargetColorMode.DEFAULT, "polished_cinnabar_wall"));
            targets.add(target("polished_deepslate", EspBlockTargetColorMode.DEFAULT, "polished_deepslate"));
            targets.add(target("polished_deepslate_slab", EspBlockTargetColorMode.DEFAULT, "polished_deepslate_slab"));
            targets.add(target("polished_deepslate_stairs", EspBlockTargetColorMode.DEFAULT, "polished_deepslate_stairs"));
            targets.add(target("polished_deepslate_wall", EspBlockTargetColorMode.DEFAULT, "polished_deepslate_wall"));
            targets.add(target("polished_diorite", EspBlockTargetColorMode.DEFAULT, "polished_diorite"));
            targets.add(target("polished_diorite_slab", EspBlockTargetColorMode.DEFAULT, "polished_diorite_slab"));
            targets.add(target("polished_diorite_stairs", EspBlockTargetColorMode.DEFAULT, "polished_diorite_stairs"));
            targets.add(target("polished_granite", EspBlockTargetColorMode.DEFAULT, "polished_granite"));
            targets.add(target("polished_granite_slab", EspBlockTargetColorMode.DEFAULT, "polished_granite_slab"));
            targets.add(target("polished_granite_stairs", EspBlockTargetColorMode.DEFAULT, "polished_granite_stairs"));
            targets.add(target("polished_sulfur", EspBlockTargetColorMode.DEFAULT, "polished_sulfur"));
            targets.add(target("polished_sulfur_slab", EspBlockTargetColorMode.DEFAULT, "polished_sulfur_slab"));
            targets.add(target("polished_sulfur_stairs", EspBlockTargetColorMode.DEFAULT, "polished_sulfur_stairs"));
            targets.add(target("polished_sulfur_wall", EspBlockTargetColorMode.DEFAULT, "polished_sulfur_wall"));
            targets.add(target("polished_tuff", EspBlockTargetColorMode.DEFAULT, "polished_tuff"));
            targets.add(target("polished_tuff_slab", EspBlockTargetColorMode.DEFAULT, "polished_tuff_slab"));
            targets.add(target("polished_tuff_stairs", EspBlockTargetColorMode.DEFAULT, "polished_tuff_stairs"));
            targets.add(target("polished_tuff_wall", EspBlockTargetColorMode.DEFAULT, "polished_tuff_wall"));
            targets.add(target("powder_snow", EspBlockTargetColorMode.DEFAULT, "powder_snow"));
            targets.add(target("prismarine", EspBlockTargetColorMode.DEFAULT, "prismarine"));
            targets.add(target("prismarine_brick_slab", EspBlockTargetColorMode.DEFAULT, "prismarine_brick_slab"));
            targets.add(target("prismarine_brick_stairs", EspBlockTargetColorMode.DEFAULT, "prismarine_brick_stairs"));
            targets.add(target("prismarine_bricks", EspBlockTargetColorMode.DEFAULT, "prismarine_bricks"));
            targets.add(target("prismarine_slab", EspBlockTargetColorMode.DEFAULT, "prismarine_slab"));
            targets.add(target("prismarine_stairs", EspBlockTargetColorMode.DEFAULT, "prismarine_stairs"));
            targets.add(target("prismarine_wall", EspBlockTargetColorMode.DEFAULT, "prismarine_wall"));
            targets.add(target("pumpkin", EspBlockTargetColorMode.DEFAULT, "pumpkin"));
            targets.add(target("purpur_block", EspBlockTargetColorMode.DEFAULT, "purpur_block"));
            targets.add(target("purpur_pillar", EspBlockTargetColorMode.DEFAULT, "purpur_pillar"));
            targets.add(target("purpur_slab", EspBlockTargetColorMode.DEFAULT, "purpur_slab"));
            targets.add(target("purpur_stairs", EspBlockTargetColorMode.DEFAULT, "purpur_stairs"));
            targets.add(target("quartz_block", EspBlockTargetColorMode.DEFAULT, "quartz_block"));
            targets.add(target("quartz_bricks", EspBlockTargetColorMode.DEFAULT, "quartz_bricks"));
            targets.add(target("quartz_pillar", EspBlockTargetColorMode.DEFAULT, "quartz_pillar"));
            targets.add(target("quartz_slab", EspBlockTargetColorMode.DEFAULT, "quartz_slab"));
            targets.add(target("quartz_stairs", EspBlockTargetColorMode.DEFAULT, "quartz_stairs"));
            targets.add(target("red_mushroom_block", EspBlockTargetColorMode.DEFAULT, "red_mushroom_block"));
            targets.add(target("red_nether_brick_slab", EspBlockTargetColorMode.DEFAULT, "red_nether_brick_slab"));
            targets.add(target("red_nether_brick_stairs", EspBlockTargetColorMode.DEFAULT, "red_nether_brick_stairs"));
            targets.add(target("red_nether_brick_wall", EspBlockTargetColorMode.DEFAULT, "red_nether_brick_wall"));
            targets.add(target("red_nether_bricks", EspBlockTargetColorMode.DEFAULT, "red_nether_bricks"));
            targets.add(target("red_sand", EspBlockTargetColorMode.DEFAULT, "red_sand"));
            targets.add(target("red_sandstone", EspBlockTargetColorMode.DEFAULT, "red_sandstone"));
            targets.add(target("red_sandstone_slab", EspBlockTargetColorMode.DEFAULT, "red_sandstone_slab"));
            targets.add(target("red_sandstone_stairs", EspBlockTargetColorMode.DEFAULT, "red_sandstone_stairs"));
            targets.add(target("red_sandstone_wall", EspBlockTargetColorMode.DEFAULT, "red_sandstone_wall"));
            targets.add(target("redstone_torches", EspBlockTargetColorMode.DEFAULT, "redstone_torch", "redstone_wall_torch"));
            targets.add(target("resin_block", EspBlockTargetColorMode.DEFAULT, "resin_block"));
            targets.add(target("resin_brick_slab", EspBlockTargetColorMode.DEFAULT, "resin_brick_slab"));
            targets.add(target("resin_brick_stairs", EspBlockTargetColorMode.DEFAULT, "resin_brick_stairs"));
            targets.add(target("resin_brick_wall", EspBlockTargetColorMode.DEFAULT, "resin_brick_wall"));
            targets.add(target("resin_bricks", EspBlockTargetColorMode.DEFAULT, "resin_bricks"));
            targets.add(target("resin_clump", EspBlockTargetColorMode.DEFAULT, "resin_clump"));
            targets.add(target("rooted_dirt", EspBlockTargetColorMode.DEFAULT, "rooted_dirt"));
            targets.add(target("sand", EspBlockTargetColorMode.DEFAULT, "sand"));
            targets.add(target("sandstone", EspBlockTargetColorMode.DEFAULT, "sandstone"));
            targets.add(target("sandstone_slab", EspBlockTargetColorMode.DEFAULT, "sandstone_slab"));
            targets.add(target("sandstone_stairs", EspBlockTargetColorMode.DEFAULT, "sandstone_stairs"));
            targets.add(target("sandstone_wall", EspBlockTargetColorMode.DEFAULT, "sandstone_wall"));
            targets.add(target("sculk", EspBlockTargetColorMode.DEFAULT, "sculk"));
            targets.add(target("sculk_vein", EspBlockTargetColorMode.DEFAULT, "sculk_vein"));
            targets.add(target("sea_lantern", EspBlockTargetColorMode.DEFAULT, "sea_lantern"));
            targets.add(target("shroomlight", EspBlockTargetColorMode.DEFAULT, "shroomlight"));
            targets.add(target("slime_block", EspBlockTargetColorMode.DEFAULT, "slime_block"));
            targets.add(target("small_amethyst_bud", EspBlockTargetColorMode.DEFAULT, "small_amethyst_bud"));
            targets.add(target("smooth_basalt", EspBlockTargetColorMode.DEFAULT, "smooth_basalt"));
            targets.add(target("smooth_quartz", EspBlockTargetColorMode.DEFAULT, "smooth_quartz"));
            targets.add(target("smooth_quartz_slab", EspBlockTargetColorMode.DEFAULT, "smooth_quartz_slab"));
            targets.add(target("smooth_quartz_stairs", EspBlockTargetColorMode.DEFAULT, "smooth_quartz_stairs"));
            targets.add(target("smooth_red_sandstone", EspBlockTargetColorMode.DEFAULT, "smooth_red_sandstone"));
            targets.add(target("smooth_red_sandstone_slab", EspBlockTargetColorMode.DEFAULT, "smooth_red_sandstone_slab"));
            targets.add(target("smooth_red_sandstone_stairs", EspBlockTargetColorMode.DEFAULT, "smooth_red_sandstone_stairs"));
            targets.add(target("smooth_sandstone", EspBlockTargetColorMode.DEFAULT, "smooth_sandstone"));
            targets.add(target("smooth_sandstone_slab", EspBlockTargetColorMode.DEFAULT, "smooth_sandstone_slab"));
            targets.add(target("smooth_sandstone_stairs", EspBlockTargetColorMode.DEFAULT, "smooth_sandstone_stairs"));
            targets.add(target("smooth_stone", EspBlockTargetColorMode.DEFAULT, "smooth_stone"));
            targets.add(target("smooth_stone_slab", EspBlockTargetColorMode.DEFAULT, "smooth_stone_slab"));
            targets.add(target("snow", EspBlockTargetColorMode.DEFAULT, "snow"));
            targets.add(target("snow_block", EspBlockTargetColorMode.DEFAULT, "snow_block"));
            targets.add(target("soul_lantern", EspBlockTargetColorMode.DEFAULT, "soul_lantern"));
            targets.add(target("soul_sand", EspBlockTargetColorMode.DEFAULT, "soul_sand"));
            targets.add(target("soul_soil", EspBlockTargetColorMode.DEFAULT, "soul_soil"));
            targets.add(target("soul_torches", EspBlockTargetColorMode.DEFAULT, "soul_torch", "soul_wall_torch"));
            targets.add(target("spruce_leaves", EspBlockTargetColorMode.DEFAULT, "spruce_leaves"));
            targets.add(target("spruce_log", EspBlockTargetColorMode.DEFAULT, "spruce_log"));
            targets.add(target("spruce_planks", EspBlockTargetColorMode.DEFAULT, "spruce_planks"));
            targets.add(target("spruce_slab", EspBlockTargetColorMode.DEFAULT, "spruce_slab"));
            targets.add(target("spruce_stairs", EspBlockTargetColorMode.DEFAULT, "spruce_stairs"));
            targets.add(target("spruce_wood", EspBlockTargetColorMode.DEFAULT, "spruce_wood"));
            targets.add(target("stained_glass", EspBlockTargetColorMode.DEFAULT, "white_stained_glass", "orange_stained_glass", "magenta_stained_glass", "light_blue_stained_glass", "yellow_stained_glass", "lime_stained_glass", "pink_stained_glass", "gray_stained_glass", "light_gray_stained_glass", "cyan_stained_glass", "purple_stained_glass", "blue_stained_glass", "brown_stained_glass", "green_stained_glass", "red_stained_glass", "black_stained_glass"));
            targets.add(target("stained_glass_pane", EspBlockTargetColorMode.DEFAULT, "white_stained_glass_pane", "orange_stained_glass_pane", "magenta_stained_glass_pane", "light_blue_stained_glass_pane", "yellow_stained_glass_pane", "lime_stained_glass_pane", "pink_stained_glass_pane", "gray_stained_glass_pane", "light_gray_stained_glass_pane", "cyan_stained_glass_pane", "purple_stained_glass_pane", "blue_stained_glass_pane", "brown_stained_glass_pane", "green_stained_glass_pane", "red_stained_glass_pane", "black_stained_glass_pane"));
            targets.add(target("stone", EspBlockTargetColorMode.DEFAULT, "stone"));
            targets.add(target("stone_brick_slab", EspBlockTargetColorMode.DEFAULT, "stone_brick_slab"));
            targets.add(target("stone_brick_stairs", EspBlockTargetColorMode.DEFAULT, "stone_brick_stairs"));
            targets.add(target("stone_brick_wall", EspBlockTargetColorMode.DEFAULT, "stone_brick_wall"));
            targets.add(target("stone_bricks", EspBlockTargetColorMode.DEFAULT, "stone_bricks"));
            targets.add(target("stone_slab", EspBlockTargetColorMode.DEFAULT, "stone_slab"));
            targets.add(target("stone_stairs", EspBlockTargetColorMode.DEFAULT, "stone_stairs"));
            targets.add(target("stripped_acacia_log", EspBlockTargetColorMode.DEFAULT, "stripped_acacia_log"));
            targets.add(target("stripped_acacia_wood", EspBlockTargetColorMode.DEFAULT, "stripped_acacia_wood"));
            targets.add(target("stripped_bamboo_block", EspBlockTargetColorMode.DEFAULT, "stripped_bamboo_block"));
            targets.add(target("stripped_birch_log", EspBlockTargetColorMode.DEFAULT, "stripped_birch_log"));
            targets.add(target("stripped_birch_wood", EspBlockTargetColorMode.DEFAULT, "stripped_birch_wood"));
            targets.add(target("stripped_cherry_log", EspBlockTargetColorMode.DEFAULT, "stripped_cherry_log"));
            targets.add(target("stripped_cherry_wood", EspBlockTargetColorMode.DEFAULT, "stripped_cherry_wood"));
            targets.add(target("stripped_crimson_hyphae", EspBlockTargetColorMode.DEFAULT, "stripped_crimson_hyphae"));
            targets.add(target("stripped_crimson_stem", EspBlockTargetColorMode.DEFAULT, "stripped_crimson_stem"));
            targets.add(target("stripped_dark_oak_log", EspBlockTargetColorMode.DEFAULT, "stripped_dark_oak_log"));
            targets.add(target("stripped_dark_oak_wood", EspBlockTargetColorMode.DEFAULT, "stripped_dark_oak_wood"));
            targets.add(target("stripped_jungle_log", EspBlockTargetColorMode.DEFAULT, "stripped_jungle_log"));
            targets.add(target("stripped_jungle_wood", EspBlockTargetColorMode.DEFAULT, "stripped_jungle_wood"));
            targets.add(target("stripped_mangrove_log", EspBlockTargetColorMode.DEFAULT, "stripped_mangrove_log"));
            targets.add(target("stripped_mangrove_wood", EspBlockTargetColorMode.DEFAULT, "stripped_mangrove_wood"));
            targets.add(target("stripped_oak_log", EspBlockTargetColorMode.DEFAULT, "stripped_oak_log"));
            targets.add(target("stripped_oak_wood", EspBlockTargetColorMode.DEFAULT, "stripped_oak_wood"));
            targets.add(target("stripped_pale_oak_log", EspBlockTargetColorMode.DEFAULT, "stripped_pale_oak_log"));
            targets.add(target("stripped_pale_oak_wood", EspBlockTargetColorMode.DEFAULT, "stripped_pale_oak_wood"));
            targets.add(target("stripped_spruce_log", EspBlockTargetColorMode.DEFAULT, "stripped_spruce_log"));
            targets.add(target("stripped_spruce_wood", EspBlockTargetColorMode.DEFAULT, "stripped_spruce_wood"));
            targets.add(target("stripped_warped_hyphae", EspBlockTargetColorMode.DEFAULT, "stripped_warped_hyphae"));
            targets.add(target("stripped_warped_stem", EspBlockTargetColorMode.DEFAULT, "stripped_warped_stem"));
            targets.add(target("sulfur", EspBlockTargetColorMode.DEFAULT, "sulfur"));
            targets.add(target("sulfur_brick_slab", EspBlockTargetColorMode.DEFAULT, "sulfur_brick_slab"));
            targets.add(target("sulfur_brick_stairs", EspBlockTargetColorMode.DEFAULT, "sulfur_brick_stairs"));
            targets.add(target("sulfur_brick_wall", EspBlockTargetColorMode.DEFAULT, "sulfur_brick_wall"));
            targets.add(target("sulfur_bricks", EspBlockTargetColorMode.DEFAULT, "sulfur_bricks"));
            targets.add(target("sulfur_slab", EspBlockTargetColorMode.DEFAULT, "sulfur_slab"));
            targets.add(target("sulfur_spike", EspBlockTargetColorMode.DEFAULT, "sulfur_spike"));
            targets.add(target("sulfur_stairs", EspBlockTargetColorMode.DEFAULT, "sulfur_stairs"));
            targets.add(target("sulfur_wall", EspBlockTargetColorMode.DEFAULT, "sulfur_wall"));
            targets.add(target("colored_terracotta", EspBlockTargetColorMode.DEFAULT, "white_terracotta", "orange_terracotta", "magenta_terracotta", "light_blue_terracotta", "yellow_terracotta", "lime_terracotta", "pink_terracotta", "gray_terracotta", "light_gray_terracotta", "cyan_terracotta", "purple_terracotta", "blue_terracotta", "brown_terracotta", "green_terracotta", "red_terracotta", "black_terracotta"));
            targets.add(target("terracotta", EspBlockTargetColorMode.DEFAULT, "terracotta"));
            targets.add(target("tinted_glass", EspBlockTargetColorMode.DEFAULT, "tinted_glass"));
            targets.add(target("torches", EspBlockTargetColorMode.DEFAULT, "torch", "wall_torch"));
            targets.add(target("tube_coral_block", EspBlockTargetColorMode.DEFAULT, "tube_coral_block"));
            targets.add(target("tuff", EspBlockTargetColorMode.DEFAULT, "tuff"));
            targets.add(target("tuff_brick_slab", EspBlockTargetColorMode.DEFAULT, "tuff_brick_slab"));
            targets.add(target("tuff_brick_stairs", EspBlockTargetColorMode.DEFAULT, "tuff_brick_stairs"));
            targets.add(target("tuff_brick_wall", EspBlockTargetColorMode.DEFAULT, "tuff_brick_wall"));
            targets.add(target("tuff_bricks", EspBlockTargetColorMode.DEFAULT, "tuff_bricks"));
            targets.add(target("tuff_slab", EspBlockTargetColorMode.DEFAULT, "tuff_slab"));
            targets.add(target("tuff_stairs", EspBlockTargetColorMode.DEFAULT, "tuff_stairs"));
            targets.add(target("tuff_wall", EspBlockTargetColorMode.DEFAULT, "tuff_wall"));
            targets.add(target("verdant_froglight", EspBlockTargetColorMode.DEFAULT, "verdant_froglight"));
            targets.add(target("warped_hyphae", EspBlockTargetColorMode.DEFAULT, "warped_hyphae"));
            targets.add(target("warped_nylium", EspBlockTargetColorMode.DEFAULT, "warped_nylium"));
            targets.add(target("warped_planks", EspBlockTargetColorMode.DEFAULT, "warped_planks"));
            targets.add(target("warped_slab", EspBlockTargetColorMode.DEFAULT, "warped_slab"));
            targets.add(target("warped_stairs", EspBlockTargetColorMode.DEFAULT, "warped_stairs"));
            targets.add(target("warped_stem", EspBlockTargetColorMode.DEFAULT, "warped_stem"));
            targets.add(target("warped_wart_block", EspBlockTargetColorMode.DEFAULT, "warped_wart_block"));
            targets.add(target("waxed_chiseled_copper", EspBlockTargetColorMode.DEFAULT, "waxed_chiseled_copper", "waxed_exposed_chiseled_copper", "waxed_weathered_chiseled_copper", "waxed_oxidized_chiseled_copper"));
            targets.add(target("waxed_copper_bars", EspBlockTargetColorMode.DEFAULT, "waxed_copper_bars", "waxed_exposed_copper_bars", "waxed_weathered_copper_bars", "waxed_oxidized_copper_bars"));
            targets.add(target("waxed_copper_block", EspBlockTargetColorMode.DEFAULT, "waxed_copper_block", "waxed_exposed_copper", "waxed_weathered_copper", "waxed_oxidized_copper"));
            targets.add(target("waxed_copper_chain", EspBlockTargetColorMode.DEFAULT, "waxed_copper_chain", "waxed_exposed_copper_chain", "waxed_weathered_copper_chain", "waxed_oxidized_copper_chain"));
            targets.add(target("waxed_copper_door", EspBlockTargetColorMode.DEFAULT, "waxed_copper_door", "waxed_exposed_copper_door", "waxed_weathered_copper_door", "waxed_oxidized_copper_door"));
            targets.add(target("waxed_copper_grate", EspBlockTargetColorMode.DEFAULT, "waxed_copper_grate", "waxed_exposed_copper_grate", "waxed_weathered_copper_grate", "waxed_oxidized_copper_grate"));
            targets.add(target("waxed_copper_lantern", EspBlockTargetColorMode.DEFAULT, "waxed_copper_lantern", "waxed_exposed_copper_lantern", "waxed_weathered_copper_lantern", "waxed_oxidized_copper_lantern"));
            targets.add(target("waxed_copper_trapdoor", EspBlockTargetColorMode.DEFAULT, "waxed_copper_trapdoor", "waxed_exposed_copper_trapdoor", "waxed_weathered_copper_trapdoor", "waxed_oxidized_copper_trapdoor"));
            targets.add(target("waxed_cut_copper", EspBlockTargetColorMode.DEFAULT, "waxed_cut_copper", "waxed_exposed_cut_copper", "waxed_weathered_cut_copper", "waxed_oxidized_cut_copper"));
            targets.add(target("waxed_cut_copper_slab", EspBlockTargetColorMode.DEFAULT, "waxed_cut_copper_slab", "waxed_exposed_cut_copper_slab", "waxed_weathered_cut_copper_slab", "waxed_oxidized_cut_copper_slab"));
            targets.add(target("waxed_cut_copper_stairs", EspBlockTargetColorMode.DEFAULT, "waxed_cut_copper_stairs", "waxed_exposed_cut_copper_stairs", "waxed_weathered_cut_copper_stairs", "waxed_oxidized_cut_copper_stairs"));
            targets.add(target("wooden_doors", EspBlockTargetColorMode.DEFAULT, "oak_door", "spruce_door", "birch_door", "jungle_door", "acacia_door", "dark_oak_door", "mangrove_door", "cherry_door", "bamboo_door", "crimson_door", "warped_door", "pale_oak_door"));
            targets.add(target("wooden_fences", EspBlockTargetColorMode.DEFAULT, "oak_fence", "spruce_fence", "birch_fence", "jungle_fence", "acacia_fence", "dark_oak_fence", "mangrove_fence", "cherry_fence", "bamboo_fence", "crimson_fence", "warped_fence", "pale_oak_fence"));
            targets.add(target("wooden_trapdoors", EspBlockTargetColorMode.DEFAULT, "oak_trapdoor", "spruce_trapdoor", "birch_trapdoor", "jungle_trapdoor", "acacia_trapdoor", "dark_oak_trapdoor", "mangrove_trapdoor", "cherry_trapdoor", "bamboo_trapdoor", "crimson_trapdoor", "warped_trapdoor", "pale_oak_trapdoor"));
            targets.add(target("wool", EspBlockTargetColorMode.DEFAULT, "white_wool", "orange_wool", "magenta_wool", "light_blue_wool", "yellow_wool", "lime_wool", "pink_wool", "gray_wool", "light_gray_wool", "cyan_wool", "purple_wool", "blue_wool", "brown_wool", "green_wool", "red_wool", "black_wool"));
            return List.copyOf(targets);
        }
    }

    private static final class FunctionalBlocksTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("anvil", EspBlockTargetColorMode.DEFAULT, "anvil"));
            targets.add(target("beds", EspBlockTargetColorMode.BED_COLOR, "white_bed", "orange_bed", "magenta_bed", "light_blue_bed", "yellow_bed", "lime_bed", "pink_bed", "gray_bed", "light_gray_bed", "cyan_bed", "purple_bed", "blue_bed", "brown_bed", "green_bed", "red_bed", "black_bed"));
            targets.add(target("cake", EspBlockTargetColorMode.DEFAULT, "cake", "candle_cake", "white_candle_cake", "orange_candle_cake", "magenta_candle_cake", "light_blue_candle_cake", "yellow_candle_cake", "lime_candle_cake", "pink_candle_cake", "gray_candle_cake", "light_gray_candle_cake", "cyan_candle_cake", "purple_candle_cake", "blue_candle_cake", "brown_candle_cake", "green_candle_cake", "red_candle_cake", "black_candle_cake"));
            targets.add(target("cartography_table", EspBlockTargetColorMode.DEFAULT, "cartography_table"));
            targets.add(target("cauldrons", EspBlockTargetColorMode.DEFAULT, "cauldron", "water_cauldron", "lava_cauldron", "powder_snow_cauldron"));
            targets.add(target("chipped_anvil", EspBlockTargetColorMode.DEFAULT, "chipped_anvil"));
            targets.add(target("composter", EspBlockTargetColorMode.DEFAULT, "composter"));
            targets.add(target("crafting_table", EspBlockTargetColorMode.DEFAULT, "crafting_table"));
            targets.add(target("damaged_anvil", EspBlockTargetColorMode.DEFAULT, "damaged_anvil"));
            targets.add(target("fletching_table", EspBlockTargetColorMode.DEFAULT, "fletching_table"));
            targets.add(target("grindstone", EspBlockTargetColorMode.DEFAULT, "grindstone"));
            targets.add(target("lightning_rod", EspBlockTargetColorMode.DEFAULT, "lightning_rod", "exposed_lightning_rod", "weathered_lightning_rod", "oxidized_lightning_rod"));
            targets.add(target("lodestone", EspBlockTargetColorMode.DEFAULT, "lodestone"));
            targets.add(target("loom", EspBlockTargetColorMode.DEFAULT, "loom"));
            targets.add(target("respawn_anchor", EspBlockTargetColorMode.DEFAULT, "respawn_anchor"));
            targets.add(target("scaffolding", EspBlockTargetColorMode.DEFAULT, "scaffolding"));
            targets.add(target("smithing_table", EspBlockTargetColorMode.DEFAULT, "smithing_table"));
            targets.add(target("sponge", EspBlockTargetColorMode.DEFAULT, "sponge"));
            targets.add(target("stonecutter", EspBlockTargetColorMode.DEFAULT, "stonecutter"));
            targets.add(target("waxed_lightning_rod", EspBlockTargetColorMode.DEFAULT, "waxed_lightning_rod", "waxed_exposed_lightning_rod", "waxed_weathered_lightning_rod", "waxed_oxidized_lightning_rod"));
            targets.add(target("wet_sponge", EspBlockTargetColorMode.DEFAULT, "wet_sponge"));
            return List.copyOf(targets);
        }
    }

    private static final class MiscTargets {
        private static List<EspBlockTarget> create() {
            List<EspBlockTarget> targets = new ArrayList<>();
            targets.add(target("barrier", EspBlockTargetColorMode.DEFAULT, "barrier"));
            targets.add(target("bedrock", EspBlockTargetColorMode.DEFAULT, "bedrock"));
            targets.add(target("bubble_column", EspBlockTargetColorMode.DEFAULT, "bubble_column"));
            targets.add(target("dragon_egg", EspBlockTargetColorMode.DEFAULT, "dragon_egg"));
            targets.add(target("dried_ghast", EspBlockTargetColorMode.DEFAULT, "dried_ghast"));
            targets.add(target("fire", EspBlockTargetColorMode.DEFAULT, "fire"));
            targets.add(target("frogspawn", EspBlockTargetColorMode.DEFAULT, "frogspawn"));
            targets.add(target("frosted_ice", EspBlockTargetColorMode.DEFAULT, "frosted_ice"));
            targets.add(target("heavy_core", EspBlockTargetColorMode.DEFAULT, "heavy_core"));
            targets.add(target("lava", EspBlockTargetColorMode.DEFAULT, "lava"));
            targets.add(target("light", EspBlockTargetColorMode.DEFAULT, "light"));
            targets.add(target("nether_portal", EspBlockTargetColorMode.DEFAULT, "nether_portal"));
            targets.add(target("petrified_oak_slab", EspBlockTargetColorMode.DEFAULT, "petrified_oak_slab"));
            targets.add(target("piston_head", EspBlockTargetColorMode.DEFAULT, "piston_head"));
            targets.add(target("reinforced_deepslate", EspBlockTargetColorMode.DEFAULT, "reinforced_deepslate"));
            targets.add(target("sniffer_egg", EspBlockTargetColorMode.DEFAULT, "sniffer_egg"));
            targets.add(target("soul_fire", EspBlockTargetColorMode.DEFAULT, "soul_fire"));
            targets.add(target("structure_void", EspBlockTargetColorMode.DEFAULT, "structure_void"));
            targets.add(target("turtle_egg", EspBlockTargetColorMode.DEFAULT, "turtle_egg"));
            targets.add(target("water", EspBlockTargetColorMode.DEFAULT, "water"));
            return List.copyOf(targets);
        }
    }

}
